### ISSUE TITLE
Morning Session: Peer to Peer Review - 12/22/22

### ISSUE THREAD

**Issue by AmanWorku** [Wahaj-Ali/Leaderboard#5]
# Your project is so perfect:
- [x] Perfect color choice
- [x] Great modularizing.
- [x] Properly Deployed.
### Kindly make the following suggestions:
- [x] Try to sort the scores from highest to lowest, as this will make it look like a real game leaderboard.

**Comment by Wahaj-Ali** [comment]
Thank you @AmanWorku for your suggestion. I am glad that I implemented it.

**Comment by AmanWorku** [comment]
@Wahaj-Ali my pleasure.
